extern crate cbindgen;

use std::{env, path::PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=DEP_TUCANOS_RPATH");
    println!("cargo:rerun-if-changed=src");
    if let Ok(rpath) = std::env::var("DEP_TUCANOS_RPATH") {
        #[cfg(any(target_os = "linux", target_os = "macos"))]
        println!("cargo:rustc-link-arg=-Wl,-rpath,{rpath}");
    }
    let mut out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    for _ in 0..3 {
        out_path.pop();
    }
    let out_file = out_path.join("tucanos.h");
    let mut config = cbindgen::Config::default();
    config.usize_is_size_t = true;
    config.language = cbindgen::Language::C;
    config.style = cbindgen::Style::Both;
    cbindgen::Builder::new()
        .with_config(config)
        .with_autogen_warning("/* This file is automatically generated when building Tucanos */")
        .with_pragma_once(true)
        .with_crate(".")
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(out_file);
}
